# Generated by Django 5.2.7 on 2025-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role_syndicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndicate',
            name='Risk_Regulatory_Attestation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='accredited',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='additional_compliance_policies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='enable_lp_network',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='firm_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='geography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='jurisdictional_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='syndicate_logos/'),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='lp_network',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='team_member',
            field=models.TextField(blank=True, null=True),
        ),
    ]
