# Generated by Django 5.2.7 on 2025-10-15 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_syndicate_risk_regulatory_attestation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'geography',
                'verbose_name_plural': 'geographies',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectors',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='syndicate',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='syndicate',
            name='sector',
        ),
        migrations.AddField(
            model_name='syndicate',
            name='time_of_register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syndicate',
            name='geographies',
            field=models.ManyToManyField(blank=True, related_name='syndicates', to='users.geography'),
        ),
        migrations.AddField(
            model_name='syndicate',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='syndicates', to='users.sector'),
        ),
    ]
