# Generated by Django 5.2.7 on 2025-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_backup_codes_customuser_totp_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totp_secret',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=20, null=True),
        ),
    ]
