# Generated by Django 5.2.7 on 2025-10-16 07:28

import django.db.models.deletion
import users.syndicate_document_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_backup_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndicateBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='users.syndicate')),
            ],
            options={
                'verbose_name': 'syndicate beneficiary',
                'verbose_name_plural': 'syndicate beneficiaries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyndicateCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_regulatory_attestation', models.BooleanField(default=False)),
                ('jurisdictional_requirements', models.BooleanField(default=False)),
                ('additional_compliance_policies', models.BooleanField(default=False)),
                ('self_knowledge_aml_policies', models.BooleanField(default=False)),
                ('is_regulated_entity', models.BooleanField(default=False)),
                ('is_ml_tf_risk', models.BooleanField(default=False)),
                ('attestation_text', models.TextField(blank=True, null=True)),
                ('attested_at', models.DateTimeField(auto_now_add=True)),
                ('attested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='users.syndicate')),
            ],
            options={
                'verbose_name': 'syndicate compliance',
                'verbose_name_plural': 'syndicate compliance records',
            },
        ),
        migrations.CreateModel(
            name='SyndicateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('syndicate_logo', 'Syndicate Logo'), ('company_certificate', 'Company Certificate of Incorporation'), ('company_bank_statement', 'Company Bank Statement'), ('company_proof_of_address', 'Company Proof of Address'), ('beneficiary_government_id', 'Beneficiary Government ID Proof'), ('beneficiary_source_of_funds', 'Beneficiary Source of Funds Proof'), ('beneficiary_tax_id', 'Beneficiary Tax ID Proof'), ('beneficiary_identity_document', 'Beneficiary Identity Document'), ('additional_policies', 'Additional Compliance Policies'), ('kyb_documents', 'KYB Verification Documents'), ('compliance_documents', 'Compliance & Attestation Documents')], max_length=50)),
                ('file', models.FileField(upload_to=users.syndicate_document_models.syndicate_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.syndicate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'syndicate document',
                'verbose_name_plural': 'syndicate documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SyndicateTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='users.syndicate')),
            ],
            options={
                'verbose_name': 'syndicate team member',
                'verbose_name_plural': 'syndicate team members',
                'ordering': ['name'],
            },
        ),
    ]
