# Generated by Django 5.2.7 on 2025-10-16 10:04

import django.db.models.deletion
import users.syndicate_image_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_syndicatebeneficiary_syndicatecompliance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndicateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('banner', 'Banner'), ('gallery', 'Gallery'), ('document', 'Document'), ('certificate', 'Certificate'), ('team_photo', 'Team Photo'), ('office_photo', 'Office Photo'), ('other', 'Other')], default='gallery', max_length=20)),
                ('image', models.ImageField(upload_to=users.syndicate_image_models.syndicate_image_upload_path)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.syndicate')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'syndicate image',
                'verbose_name_plural': 'syndicate images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
