# Generated by Django 5.2.7 on 2025-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='document_file',
        ),
        migrations.AddField(
            model_name='kyc',
            name='I_Agree_To_Investee_Terms',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='Investee_Company_Contact_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='Investee_Company_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='Unlocksley_To_Sign_a_Deed_Of_adherence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='certificate_of_incorporation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='company_bank_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='company_proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kyc',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='notary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='owner_identity_doc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='owner_proof_of_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='sie_eligibilty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
