# Generated by Django 5.2.7 on 2025-10-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_remove_kyc_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='document_type',
        ),
    ]
